### ISSUE TITLE
solve this error and update 

### ISSUE THREAD

**Issue by sangamahesh** [gotr00t0day/spyhunt#1]
Found nodejs
Found npm
Traceback (most recent call last):
  File "/root/spyhunt/install.py", line 34, in <module>
    command("npm install broken-link-checker -g")
    ^^^^^^^
NameError: name 'command' is not defined. Did you mean: 'commands'?

python3 spyhunt.py -h
Traceback (most recent call last):
  File "/root/spyhunt/spyhunt.py", line 25, in <module>
    import execjs
ModuleNotFoundError: No module named 'execjs'

**Comment by PushkraJ99** [comment]
Errors Fixed Here Check This --> https://github.com/PushkraJ99/spyhunt

Also Try Paramspider Upgraded Version  copy and Run in Terminal
`git clone https://github.com/PushkraJ99/ParamSpider ; cd ParamSpider ; pip install . ; paramspider -h`

**Comment by mojidoji** [comment]
> Errors Fixed Here Check This --> https://github.com/PushkraJ99/spyhunt
> 
> Also Try Paramspider Upgraded Version --> https://github.com/PushkraJ99/ParamSpider
> 
> Try Oneliner of Paramspider copy and Run in Terminal `git clone https://github.com/PushkraJ99/ParamSpider ; cd ParamSpider ; pip install . ; paramspider -h`

it has the problem still tho

**Comment by sasholy** [comment]
> > Errors Fixed Here Check This --> https://github.com/PushkraJ99/spyhunt
> > Also Try Paramspider Upgraded Version --> https://github.com/PushkraJ99/ParamSpider
> > Try Oneliner of Paramspider copy and Run in Terminal `git clone https://github.com/PushkraJ99/ParamSpider ; cd ParamSpider ; pip install . ; paramspider -h`
> 
> it has the problem still tho

┌──(kali㉿kali)-[~/spyhunt]
└─$ python3 spyhunt.py -s palantir.com --save filename.txt
Traceback (most recent call last):
  File "/home/kali/spyhunt/spyhunt.py", line 25, in <module>
    import execjs
ModuleNotFoundError: No module named 'execjs'

it has the problem still tho

**Comment by sasholy** [comment]
> pip install PyExecJS

pip3 install PyExecJS

thx.

**Comment by gotr00t0day** [comment]
> Found nodejs Found npm Traceback (most recent call last): File "/root/spyhunt/install.py", line 34, in command("npm install broken-link-checker -g") ^^^^^^^ NameError: name 'command' is not defined. Did you mean: 'commands'?
> 
> python3 spyhunt.py -h Traceback (most recent call last): File "/root/spyhunt/spyhunt.py", line 25, in import execjs ModuleNotFoundError: No module named 'execjs'

Did you install the requirements? pip3 install -r requirements.txt
